import type { FilePickerLabels } from './types'

/**
 * The built-in (English) label set. Override any subset via the `labels` option:
 *
 * ```ts
 * new FilePicker({ adapter, labels: { upload: 'Téléverser', done: 'Terminé' } })
 * ```
 */
export const defaultLabels: FilePickerLabels = {
  title: 'Media Library',
  filters: 'Filters',
  upload: 'Upload',
  done: 'Done',
  selectAction: (n) => (n > 0 ? `Select ${n}` : 'Done'),
  clearSelection: 'Clear selection',
  selected: (n) => `${n} selected`,
  gridLabel: 'Media',
  triggerLabel: 'Select File',
  searchPlaceholder: 'Search files…',
  tagPlaceholder: 'Tag…',
  allTypes: 'All types',
  clearFilters: 'Clear filters',
  refresh: 'Refresh',
  closeFilters: 'Close filters',
  loading: 'Loading media',
  results: (n) => (n === 1 ? '1 result' : `${n} results`),
  errorTitle: "Couldn't load media",
  errorBody: 'Something went wrong while loading your library.',
  retry: 'Try again',
  emptyTitle: 'Your library is empty',
  emptyBody: 'Upload your first file to get started.',
  emptyReadonlyBody: 'Nothing here yet.',
  emptyUpload: 'Upload files',
  filteredTitle: 'No files match your filters',
  filteredBody: 'Try a different search, or clear the filters.',
  first: 'First',
  previous: 'Previous',
  next: 'Next',
  last: 'Last',
  itemsPerPage: 'Items per page',
  perPageOption: (n) => `${n} / page`,
  pageStatus: (page, last, total) =>
    total > 0 ? `${page} / ${last} · ${total} item${total === 1 ? '' : 's'}` : `${page} / ${last}`,
  preview: 'Preview',
  open: 'Open',
  edit: 'Edit',
  delete: 'Delete',
  remove: 'Remove',
  close: 'Close',
  cancel: 'Cancel',
  ok: 'OK',
  confirm: 'Confirm',
  uploadTitle: 'Upload Media',
  destinationFolder: 'Destination folder',
  uploadToFolder: 'Upload to folder',
  dropHint: 'Click to select files, or drag & drop',
  uploaded: (n) => (n === 1 ? 'Uploaded 1 file' : `Uploaded ${n} files`),
  uploadFailed: 'Upload failed',
  uploadSkipped: (n) => `${n} file${n === 1 ? '' : 's'} skipped  wrong type`,
  editTitle: 'Edit Media',
  filename: 'Filename',
  altText: 'Alt text',
  altPlaceholder: 'Alt text (accessibility)',
  saveAlt: 'Save alt text',
  saveFilename: 'Save filename',
  folder: 'Folder',
  tags: 'Tags',
  addTagHint: 'Add a tag and press Enter',
  saveTags: 'Save tags',
  saved: 'Changes saved',
  saveFailed: 'Save failed',
  editMeta: (type, mime, size) => `Type: ${type} · ${mime} · ${size}`,
  deleteFileTitle: 'Delete file',
  deleteFileConfirm: (name) => `Delete "${name}"? This cannot be undone.`,
  fileDeleted: 'File deleted',
  deleteFailed: 'Delete failed',
  createFolderFailed: 'Could not create folder',
  deleteFolderFailed: 'Could not delete folder',
  closePreview: 'Close preview',
  maxSelection: (n) => `You can select up to ${n} item${n === 1 ? '' : 's'}`,
  allFolders: 'All Folders',
  uncategorized: 'Uncategorized',
  folderLabel: 'Folder',
  folderSearch: 'Search or create…',
  createFolder: (name) => `Create folder "${name}"`,
  noFolders: 'No folders found',
  deleteFolderControl: 'Delete folder',
  deleteFolderTitle: 'Delete folder',
  deleteFolderConfirm: (name) => `Delete "${name}"? Files inside move to Uncategorized.`,
  renameFolderControl: 'Rename folder',
  renameFolderTitle: 'Rename folder',
  renameFolderMessage: 'New folder name',
  renameFolderFailed: 'Could not rename folder',
}
